services:
  main:
    container_name: main
    restart: always
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:${SERVER_PORT}
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    container_name: todo-app-monolith-db
    image: postgres:16.4-alpine3.20
    restart: always
    env_file:
      - .env
    shm_size: 256mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
