services:
  main:
    container_name: main
    restart: always
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:3000
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    env_file:
      - .env
    shm_size: 256mb
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432